apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: node-api
        image: swimlane:some_version              # image from previous, we need to transfer image from local to worker nodes 
        ports:
        - containerPort: 3000