---

- hosts: worked_nodes
  gather_facts: true 
  user: root
  
  tasks:
    - name: Install NTP
      apt: package=ntp,ntpdate state=present update_cache=yes
      tags: ntp
    
    - name: Make sure NTP is started up
      service: name=ntp state=started enabled=yes
      tags: ntp